# INPUT
print("INPUT")
nama = input("Nama                 : ")
NIM = input("NIM                  : ")
paralel = input("Kelas Paralel        : ")
TTL = input("Tempat/Tanggal Lahir : ")
alamat = input("Alamat               : ")
hobby = input("Hobby                : ")
no_hp = input("No. HP               : ")
print()
# OUTPUT
print("OUTPUT")
print("Nama                 :", nama)
print("NIM                  :", NIM)
print("Kelas Paralel        :", paralel)
print("Tempat/Tanggal Lahir :", TTL)
print("Alamat               :", alamat)
print("Hobby                :", hobby)
print("No. HP               :", no_hp)