print("#################################\n")
print("#\t\t\t\t#\n")
print("#\t  Randy Febrian  \t#\n")
print("#\t  2310817110013  \t#\n")
print("#\t\t\t\t#\n")
print("#################################\n")